### ISSUE TITLE
jcoco 커버리지

### ISSUE THREAD

**Issue by rkaehdaos** [rkaehdaos/spring3-edu-test#5]

**Comment by rkaehdaos** [comment]
# 모든 branch 

## 1
```yaml
on:
  push:
    branches:
      - '*'
```
## 2
```yaml
on:
  push:
   
```
